# SPDX-License-Identifier: GPL-2.0
subdir-y += allwinner
subdir-y += sifive
subdir-y += starfive
subdir-y += canaan
subdir-y += microchip
subdir-y += renesas
subdir-y += virt

obj-$(CONFIG_BUILTIN_DTB) := $(addsuffix /, $(subdir-y))
